### ISSUE TITLE
macos install falls

### ISSUE THREAD

**Issue by wminshew** [rkyleg/asdf-julia#12]
macos catalina 10.15.5 (19F101) - any other information I can provide?

```
$ asdf install julia 1.5.0
Downloading from:
https://julialang-s3.julialang.org/bin/mac/x64/1.5/julia-1.5.0-mac64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96.0M  100 96.0M    0     0  5484k      0  0:00:17  0:00:17 --:--:-- 5935k
hdiutil: unmount: Only a single file can be specified.
Usage:	hdiutil unmount [options] <mountpoint>
	hdiutil unmount -help
```

**Comment by lassepe** [comment]
There is https://github.com/rkyleg/asdf-julia/pull/11. Have you tried if it fixes your problem?

**Comment by wminshew** [comment]
thanks I'll test it out. Is there a way to add the branch directly from `asdf plugin-add <git-url>` or do I need to to clone the repo first? (searching for the answer now but not having much luck & figured I'd ask in case you already knew)

**Comment by wminshew** [comment]
cloned locally & it works. Thank you!

**Comment by tobbbles** [comment]
This PR also fixed my issue of shims not being created, as julia was being installed to `julia/bin/julia`.

**Comment by lassepe** [comment]
I guess it makes sense to keep this issue open until #11 is merged.
