### ISSUE TITLE
Shims not being created on macOS Catalina

### ISSUE THREAD

**Issue by willus10245** [rkyleg/asdf-julia#14]
macOS 10.15.7

```sh
$ asdf install julia 1.5.3  
Downloading from:
https://julialang-s3.julialang.org/bin/mac/x64/1.5/julia-1.5.3-mac64.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 96.2M  100 96.2M    0     0  34.5M      0  0:00:02  0:00:02 --:--:-- 34.5M
"/Volumes/Julia-1.5.3 1" unmounted successfully.

$ julia
zsh: command not found: julia
```

Nothing in `shims` related to julia. Running `asdf reshim julia` has no effect.

`~/.asdf/installs/julia` looks like: 
```
1.5.3
    └── julia
        ├── LICENSE.md
        ├── bin
        │   └── julia
        ├── etc
        ├── include
        ├── lib
        ├── libexec
        └── share
```

**Comment by lassepe** [comment]
Just to make sure that this is a problem with this plugin, can you confirm that you don't have this issue with other plugins? Maybe you can try `asdf plugin add R` and see what it does. That said, there is a good chance that there is still something wrong with the plugin under macOS since most of the testing has been under Linux (and the CI doesn't catch these errors because of #13 ). Therefore, this is a good opportunity to debug things.

**Comment by willus10245** [comment]
Ok well I had some dependency issues trying to install R, so I wasn't able to get that one to work either. But I have several other plugins that I've used with no issues (elixir, ruby, python, rust, nodejs, postgres). Idk how the shims are generated, or if this matters, but one thing I noticed is that the julia install is nested one level deeper than the rest of my plugins. The rest all look like `installs/<plugin>/<version>/(bin|lib|etc)`.

**Comment by lassepe** [comment]
That's a good observation. I just pushed a potential fix to my fork. You can try it out by installing the plugin via a direct URL (you may have to remove the old one first):

```
asdf plugin add julia https://github.com/lassepe/asdf-julia
```

If that fix works for you, let me know. Then I'll open a PR here so that you can switch back to the main branch soon.

**Comment by willus10245** [comment]
That worked with one small modification. On line 145 of `install`, the wild card needs to be outside the quotes.

```
cp -R "$source_path"/* $install_path/
```

https://stackoverflow.com/questions/34254164/what-is-cp-cannot-stat-error-in-unix-i-get-this-error-when-trying-to-copy-thin

**Comment by rkyleg** [comment]
@lassepe if you want to open a pull request...go ahead. I don't have a Mac to test on anymore...so thank you for your help on this and thank you for reporting @willus10245 .
