### ISSUE TITLE
Listing versions: tempfile utility is not available by default

### ISSUE THREAD

**Issue by acidghost** [rkyleg/asdf-julia#29]
The `list-all` command requires that `tempfile` is installed.
It's not installed by default and I'm also not sure how to install it: on Fedora 35 and macOS Homebrew it's not available.

Is there a specific reason to why `tempfile` is used over something more common, such as `mktemp`?

I'd be willing to make a PR to make the change.

**Comment by lassepe** [comment]
See #26

**Comment by acidghost** [comment]
Sorry, I also had the 👍  on the suggested fix comment... 🤦
