### ISSUE TITLE
Version 1.2.0 Installation error mkdir 

### ISSUE THREAD

**Issue by AxelRHD** [rkyleg/asdf-julia#5]
I just updated the plugin and while trying to install julia version 1.2.0 I got the follogwing error:

`mkdir: the directory »/home/username/.asdf/installs/julia/1.2.0/julia“ cannot be created: file already exists` (translated from German language).

Can I somehow fix this issue?

EDIT: trying to install other versions (e. g. 1.1.1) causes the same error.

**Comment by israelfaria** [comment]
Hitting the bug here.

**Comment by AxelRHD** [comment]
I downgraded the plugin-folder. Installation of version 1.2.0 works now. Maybe the best solution until the bug is fixed.

**Comment by elcritch** [comment]
Still getting this error. I reverted the repo to version `8af37733654cd08efe6e09060e3ca9c33295178b` to get it working again.

**Comment by lassepe** [comment]
Can't reproduce. Maybe stale?

**Comment by alecmev** [comment]
Yeah, the only `mkdir` in the repository is [commented out as of August 31](https://github.com/rkyleg/asdf-julia/commit/41813efd2cdf2ff0223b20a01243d3e9269b4afb#diff-81fd2adb13518cfcf88c004b912c4d9fR64).

**Comment by AxelRHD** [comment]
Problem is solved now.
