### ISSUE TITLE
Cannot install Julia using Dockerfile

### ISSUE THREAD

**Issue by drujensen** [rkyleg/asdf-julia#8]
When trying to install Julia on a docker image using asdf, the prompt to install on desktop is shown but there is no way to bypass the prompt.  It requires interaction to finish the install.  I tried using `-q` flag to be more quiet but this didn't work.

How can I install this without getting a prompt?

**Comment by rkyleg** [comment]
@drujensen let me know if @lassepe pull request fixes your issue.
